export const actionTypes = {
  SAVE: 'GAME_APP/GAME_PAGE/SAVE',
  SAVE_SUCCESS: 'GAME_APP/GAME_PAGE/SAVE_SUCCESS',
  SAVE_ERROR: 'GAME_APP/GAME_PAGE/SAVE_ERROR',
  CHANGE: 'GAME_APP/GAME_PAGE/CHANGE'
};

export const key = 'GAME_PAGE';
