export const actionTypes = {
  SIGN: 'GAME_APP/SIGN_PAGE/SIGN',
  SIGN_SUCCESS: 'GAME_APP/SIGN_PAGE/SIGN_SUCCESS',
  SIGN_ERROR: 'GAME_APP/SIGN_PAGE/SIGN_ERROR',
  CHANGE: 'GAME_APP/SIGN_PAGE/CHANGE'
};

export const key = 'SIGN_PAGE';
