export const actionTypes = {
  LOGIN: 'GAME_APP/LOGIN_PAGE/LOGIN',
  LOGIN_SUCCESS: 'GAME_APP/LOGIN_PAGE/LOGIN_SUCCESS',
  LOGIN_ERROR: 'GAME_APP/LOGIN_PAGE/LOGIN_ERROR',
  CHANGE: 'GAME_APP/LOGIN_PAGE/CHANGE'
};

export const key = 'LOGIN_PAGE';
